config/routes.rb
Rails.application.routes.draw do
  resources :todos do
    member do
      patch :toggle_check
    end
  end

  root 'todos#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/todo.rb
class Todo < ApplicationRecord
	def toggle_check!
    self.check = !self.check
    save
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  before_action :set_todo, only: %i[ show edit update destroy ]

  # GET /todos or /todos.json
  def index
    @todos = Todo.all
  end

  # GET /todos/1 or /todos/1.json
  def show
    
  end

  # GET /todos/new
  def new
    @todo = Todo.new
  end

  # GET /todos/1/edit
  def edit
  end

  # POST /todos or /todos.json
  def create
    @todo = Todo.new(todo_params)

    respond_to do |format|
      if @todo.save
        format.html { redirect_to todo_url(@todo), notice: "Todo was successfully created." }
        format.json { render :show, status: :created, location: @todo }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @todo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /todos/1 or /todos/1.json
  def update
    respond_to do |format|
      if @todo.update(todo_params)
        format.html { redirect_to todo_url(@todo), notice: "Todo was successfully updated." }
        format.json { render :show, status: :ok, location: @todo }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @todo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /todos/1 or /todos/1.json
  def destroy
    @todo.destroy!

    respond_to do |format|
      format.html { redirect_to todos_url, notice: "Todo was successfully destroyed." }
      format.json { head :no_content }
    end
  end

def toggle_check
  @todo = Todo.find(params[:id])

  if @todo.toggle_check!
    render json: { success: true, checked: @todo.check }
  else
    errors = @todo.errors.full_messages
    logger.error("Toggle Check Failed: #{errors.join(', ')}")
    render json: { success: false, errors: errors }, status: :unprocessable_entity
  end
end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_todo
      @todo = Todo.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def todo_params
      params.require(:todo).permit(:task, :check)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar bg-body-tertiary">
  <div class="container-fluid">
    <a class="navbar-brand" href="<%= root_path %>">To Do List</a>
    <a class="navbar-brand" href="<%= new_todo_path %>">Add New Task</a>
  </div>
</nav>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>My To do List</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_importmap_tags %>
    <%= render 'layouts/header' %>
  </head>
  <body>
  <%= yield %>
  </body>
</html>

app/views/todos/_form.html.erb
  <%= form_with(model: todo) do |form| %>
  <% if todo.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(todo.errors.count, "error") %> prohibited this todo from being saved:</h2>

      <ul>
        <% todo.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  
  <!--
    <%= form.label :task, style: "display: block" %>
    <%= form.text_field :task %>
  -->
    <%= form.label :task, "Task", class: "form-label form-control-label hidden-label" %>
    <%= form.text_field :task, class: "form-control" %>
    <%= form.submit "Submit", class: "btn btn-primary"%>
  
<% end %>

app/views/todos/_todo.html.erb
<div id="<%= dom_id todo %>">
<!--  <p>
    <strong>Task:</strong>
    <%= todo.task %>
  </p>

  <p>
    <strong>Check:</strong>
    <%= todo.check %>
  </p> -->
  <table class="table">
    <tr>
      <td>
        <%= form_for(todo, url: toggle_check_todo_path(todo), method: :patch) do |f| %>
          <%= f.check_box :check, { class: "check-box", onchange: "this.form.submit()" } %>
        <% end %>
      </td>
      <td>
        <a class="navbar-brand" href="<%= todo_path(todo) %>"><%= todo.task %></a>
      </td>
    </tr>
  </table>

</div>

app/views/todos/edit.html.erb
<div class="container-fluid">
<h1>Edit Task</h1>

<%= render "form", todo: @todo %>

<br>
<!--
<div>
  <%= link_to "Show this todo", @todo %> |
  <%= link_to "Back to todos", todos_path %>
</div> -->
</div>

app/views/todos/index.html.erb
<div class="container-fluid">
  <table class="table">
    <thead>
      <!-- ... -->
    </thead>
    <tbody>
      <% @todos.each do |todo| %>
        <tr>
          <td>
            <%= form_for(todo, remote: true, url: toggle_check_todo_path(todo), method: :patch) do |f| %>
              <%= f.check_box :check, class: "check-box", data: { toggle_path: toggle_check_todo_path(todo) } %>
            <% end %>
          </td>
          <td>
            <a class="navbar-brand" href="<%= todo_path(todo) %>"><%= todo.task %></a>
          </td>
          <td>
            <!-- Add any additional columns as needed -->
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>


<!-- Include the following JavaScript at the bottom of your HTML file -->
<script>
 document.addEventListener('DOMContentLoaded', function() {
  document.querySelectorAll('.check-box').forEach(function(checkbox) {
    checkbox.addEventListener('change', function() {
      var togglePath = checkbox.dataset.togglePath;
      var csrfToken = document.querySelector('meta[name="csrf-token"]').content;

      fetch(togglePath, {
        method: 'PATCH',
        headers: {
          'X-CSRF-Token': csrfToken,
          'Content-Type': 'application/json',
        },
      })
      .then(response => response.ok ? response.json() : Promise.reject('Request failed'))
      .then(data => {
      })
      .catch(error => console.error('AJAX error:', error));
    });
  });
});

</script>

app/views/todos/new.html.erb
<div class="container-fluid">
<h1>Add New Task</h1>
<%= render "form", todo: @todo %>

<br>
<!--
<div>
  <%= link_to "Back to todos", todos_path %>
</div>
-->
</div>

app/views/todos/show.html.erb
<!-- <p style="color: green"><%= notice %></p> -->
<div class="container-fluid">
  <%= render @todo %>

  <!-- 
    <%= link_to "Edit this todo", edit_todo_path(@todo) %> |
    <%= link_to "Back to todos", todos_path %> 
  -->
  <div class="button-container">
    <%= button_to "Edit", edit_todo_path(@todo), method: :get, class: "btn btn-primary" %>
    <%= button_to "Destroy this todo", @todo, method: :delete,
       class: "btn btn-danger"%>

  </div>
</div>